//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WendigoJaeger.TranslationTool {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WendigoJaeger.TranslationTool.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string buttonCancel {
            get {
                return ResourceManager.GetString("buttonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string buttonOK {
            get {
                return ResourceManager.GetString("buttonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Byte Value.
        /// </summary>
        public static string checkBoxShowByte {
            get {
                return ResourceManager.GetString("checkBoxShowByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Grid.
        /// </summary>
        public static string checkBoxShowGrid {
            get {
                return ResourceManager.GetString("checkBoxShowGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Files (*.asm,*.s)|*.asm;*.s.
        /// </summary>
        public static string filterAssemblyFile {
            get {
                return ResourceManager.GetString("filterAssemblyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics Data (*.*)|*.*.
        /// </summary>
        public static string filterGraphicsData {
            get {
                return ResourceManager.GetString("filterGraphicsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WendigoJaeger Translation Project (*.wtp)|*.wtp.
        /// </summary>
        public static string filterProjectFile {
            get {
                return ResourceManager.GetString("filterProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Settings.
        /// </summary>
        public static string groupBoxCommonSettings {
            get {
                return ResourceManager.GetString("groupBoxCommonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Height:.
        /// </summary>
        public static string labelCharacterHeight {
            get {
                return ResourceManager.GetString("labelCharacterHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Width:.
        /// </summary>
        public static string labelCharacterWidth {
            get {
                return ResourceManager.GetString("labelCharacterWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Name:.
        /// </summary>
        public static string labelEntryName {
            get {
                return ResourceManager.GetString("labelEntryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path:.
        /// </summary>
        public static string labelFilePath {
            get {
                return ResourceManager.GetString("labelFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Graphics:.
        /// </summary>
        public static string labelFontGraphics {
            get {
                return ResourceManager.GetString("labelFontGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Offset:.
        /// </summary>
        public static string labelFontOffset {
            get {
                return ResourceManager.GetString("labelFontOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics:.
        /// </summary>
        public static string labelGraphics {
            get {
                return ResourceManager.GetString("labelGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Palette:.
        /// </summary>
        public static string labelPalette {
            get {
                return ResourceManager.GetString("labelPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom:.
        /// </summary>
        public static string labelZoom {
            get {
                return ResourceManager.GetString("labelZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WendigoJaeger Translation Tool.
        /// </summary>
        public static string mainWindowTitle {
            get {
                return ResourceManager.GetString("mainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About WendigoJaeger Translation Tool.
        /// </summary>
        public static string mnuAbout {
            get {
                return ResourceManager.GetString("mnuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        public static string mnuBuild {
            get {
                return ResourceManager.GetString("mnuBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build All.
        /// </summary>
        public static string mnuBuildAll {
            get {
                return ResourceManager.GetString("mnuBuildAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build and run.
        /// </summary>
        public static string mnuBuildAndRun {
            get {
                return ResourceManager.GetString("mnuBuildAndRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string mnuEdit {
            get {
                return ResourceManager.GetString("mnuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string mnuFile {
            get {
                return ResourceManager.GetString("mnuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string mnuFileExit {
            get {
                return ResourceManager.GetString("mnuFileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string mnuHelp {
            get {
                return ResourceManager.GetString("mnuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string mnuProject {
            get {
                return ResourceManager.GetString("mnuProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Assembly File....
        /// </summary>
        public static string mnuProjectAddAssemblyFile {
            get {
                return ResourceManager.GetString("mnuProjectAddAssemblyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Font....
        /// </summary>
        public static string mnuProjectAddFont {
            get {
                return ResourceManager.GetString("mnuProjectAddFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Graphics....
        /// </summary>
        public static string mnuProjectAddGraphics {
            get {
                return ResourceManager.GetString("mnuProjectAddGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Language....
        /// </summary>
        public static string mnuProjectAddLanguage {
            get {
                return ResourceManager.GetString("mnuProjectAddLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Script....
        /// </summary>
        public static string mnuProjectAddScript {
            get {
                return ResourceManager.GetString("mnuProjectAddScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Settings....
        /// </summary>
        public static string mnuProjectSettings {
            get {
                return ResourceManager.GetString("mnuProjectSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string mnuRun {
            get {
                return ResourceManager.GetString("mnuRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script.
        /// </summary>
        public static string mnuScript {
            get {
                return ResourceManager.GetString("mnuScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract.
        /// </summary>
        public static string mnuScriptExtract {
            get {
                return ResourceManager.GetString("mnuScriptExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Entry.
        /// </summary>
        public static string mnuScriptNext {
            get {
                return ResourceManager.GetString("mnuScriptNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Entry.
        /// </summary>
        public static string mnuScriptPrevious {
            get {
                return ResourceManager.GetString("mnuScriptPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Settings....
        /// </summary>
        public static string mnuScriptSettings {
            get {
                return ResourceManager.GetString("mnuScriptSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string outputHeader {
            get {
                return ResourceManager.GetString("outputHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Files.
        /// </summary>
        public static string projectHeaderCustomAssemblyFIle {
            get {
                return ResourceManager.GetString("projectHeaderCustomAssemblyFIle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string projectHeaderFont {
            get {
                return ResourceManager.GetString("projectHeaderFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics.
        /// </summary>
        public static string projectHeaderGraphics {
            get {
                return ResourceManager.GetString("projectHeaderGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palettes.
        /// </summary>
        public static string projectHeaderPalettes {
            get {
                return ResourceManager.GetString("projectHeaderPalettes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripts.
        /// </summary>
        public static string projectHeaderScripts {
            get {
                return ResourceManager.GetString("projectHeaderScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launching emulator &apos;{0} - {1}&apos;....
        /// </summary>
        public static string runMessage {
            get {
                return ResourceManager.GetString("runMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string toolbarLanguage {
            get {
                return ResourceManager.GetString("toolbarLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final.
        /// </summary>
        public static string translationStateFinal {
            get {
                return ResourceManager.GetString("translationStateFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string translationStateInProgress {
            get {
                return ResourceManager.GetString("translationStateInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Review.
        /// </summary>
        public static string translationStateReview {
            get {
                return ResourceManager.GetString("translationStateReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Translate.
        /// </summary>
        public static string translationStateToTranslate {
            get {
                return ResourceManager.GetString("translationStateToTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original.
        /// </summary>
        public static string translationToolOriginal {
            get {
                return ResourceManager.GetString("translationToolOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations.
        /// </summary>
        public static string translationToolTranslation {
            get {
                return ResourceManager.GetString("translationToolTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Objects.
        /// </summary>
        public static string windowBrowseObject {
            get {
                return ResourceManager.GetString("windowBrowseObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Assembly File Settings.
        /// </summary>
        public static string windowCreateAssemblyFile {
            get {
                return ResourceManager.GetString("windowCreateAssemblyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Font Settings.
        /// </summary>
        public static string windowCreateFontSettings {
            get {
                return ResourceManager.GetString("windowCreateFontSettings", resourceCulture);
            }
        }
    }
}
