//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WendigoJaeger.TranslationTool {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LibResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LibResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WendigoJaeger.TranslationTool.LibResource", typeof(LibResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembling final ROM with bass.
        /// </summary>
        public static string bassAssembling {
            get {
                return ResourceManager.GetString("bassAssembling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bass.exe returned errors. Check the output for more details..
        /// </summary>
        public static string bassError {
            get {
                return ResourceManager.GetString("bassError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The script bank {0} is overflowing..
        /// </summary>
        public static string bassErrorOverflow {
            get {
                return ResourceManager.GetString("bassErrorOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1BPP Monochrome.
        /// </summary>
        public static string gfx1bpp {
            get {
                return ResourceManager.GetString("gfx1bpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2BPP Neo Geo Pocket Color.
        /// </summary>
        public static string gfx2bppNeoGeoPocketColor {
            get {
                return ResourceManager.GetString("gfx2bppNeoGeoPocketColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2BPP NES.
        /// </summary>
        public static string gfx2bppNES {
            get {
                return ResourceManager.GetString("gfx2bppNES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2BPP SNES/GB/GBC.
        /// </summary>
        public static string gfx2bppNintendo {
            get {
                return ResourceManager.GetString("gfx2bppNintendo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2BPP Virtual Boy.
        /// </summary>
        public static string gfx2bppVirtualBoy {
            get {
                return ResourceManager.GetString("gfx2bppVirtualBoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3BPP SNES.
        /// </summary>
        public static string gfx3bppSNES {
            get {
                return ResourceManager.GetString("gfx3bppSNES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4BPP Sega Master System/Game Gear/Wonderswan Color.
        /// </summary>
        public static string gfx4bppGameGear {
            get {
                return ResourceManager.GetString("gfx4bppGameGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4BPP Sega Genesis/Megadrive/X68000.
        /// </summary>
        public static string gfx4bppGenesis {
            get {
                return ResourceManager.GetString("gfx4bppGenesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4BPP SNES/PC Engine.
        /// </summary>
        public static string gfx4bppSNES {
            get {
                return ResourceManager.GetString("gfx4bppSNES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8BPP SNES.
        /// </summary>
        public static string gfx8bppSNES {
            get {
                return ResourceManager.GetString("gfx8bppSNES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character &apos;{0}&apos; not found in correspondence table &apos;{1}&apos;. Context: Entry &apos;{2}/{3} ({4})&apos; line: {5} column: {6}.
        /// </summary>
        public static string scriptConverterError {
            get {
                return ResourceManager.GetString("scriptConverterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Extractor 16-bit Pointer Little Endian.
        /// </summary>
        public static string scriptExtractorPointer16LittleEndian {
            get {
                return ResourceManager.GetString("scriptExtractorPointer16LittleEndian", resourceCulture);
            }
        }
    }
}
